### ISSUE TITLE
Error when running Backport docker container

### ISSUE THREAD

**Issue by xgidiussenjensent-els** [sqren/backport#309]
Hi

I'm having trouble running the backport docker container. 

When initialising a container from the 'sqren/backport' image, I get the following error: 
```
Invalid option "branches"
```
So, I have built the docker image locally from main, but when I run that, I get: 
```
/entrypoint.sh: line 10: backport: command not found
```

I am running it like in `backport-alias.sh`:
```
docker run -it --rm -v $(pwd):/app:ro -v $BACKPORT_FOLDER:/root/.backport -v $GITCONFIG:/etc/gitconfig sqren/backport "$@"
```
My .backport.json looks something like this: 
```
{
  "fork": false,
  "upstream": "x",
  "targetBranchChoices": [
    "xx-SNAPSHOT",
    "xx-RELEASE"
  ],
  "targetPRLabels": ["something", "something-else"]
}
```
I hope you can help with this. 
Thanks

BR
Thomas Jensen

**Comment by sqren** [comment]
Hey there,

I just released 7.3.2 and updated the command:

https://github.com/sqren/backport/blob/bcd6235b868665a65c29ec2b153ca5d39e37900b/docker/backport-alias.sh#L11

Can you give it a try and let me know if it works?

**Comment by xgidiussenjensent-els** [comment]
> Hey there,
> 
> I just released 7.3.2 and updated the command:
> 
> https://github.com/sqren/backport/blob/bcd6235b868665a65c29ec2b153ca5d39e37900b/docker/backport-alias.sh#L11
> 
> Can you give it a try and let me know if it works?

Hi 
That was fast. 
I tried the new code with the updated command. Unfortunately, I get: 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown.
```

**Comment by xgidiussenjensent-els** [comment]
This dockerfile works for me: 

```
FROM node:latest

COPY ./entrypoint.sh ./entrypoint.sh

RUN mkdir /app
WORKDIR /app


RUN npm install backport -g
ENTRYPOINT ["/entrypoint.sh"]
CMD []
```

**Comment by sqren** [comment]
Hey there,

I forget to get back to you but I did update the docker setup:
https://github.com/sqren/backport/tree/main/docker

I'm able to make it work like:
```
./backport.sh --repo backport-org/backport-demo --no-fork
```

Can you give it a try?

**Comment by xgidiussenjensent-els** [comment]
Hi again
I tried pulling the newest image and I ran it as before, i.e. 
`docker run -it --rm -v $PURE_BASE_PATH:/app:ro -v $BACKPORT_FOLDER:/root/.backport -v $GITCONFIG:/etc/gitconfig sqren/backport "$@"`

I still get the same error message as before: 
`Invalid option "branches"`

**Comment by sqren** [comment]
Okay, I think the problem was that I hadn't published the image to docker hub. Try running this now:

```
docker run -it --rm -v $(pwd):/app:ro -v ~/.backport:/root/.backport sqren/backport "$@"
```

_Note: you might have to change `$(pwd)` and `~/.backport` if you are on Windows._

**Comment by xgidiussenjensent-els** [comment]
There does still seem to be something with the build. 
When I run your command above, I get 
```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```
When I add a --platform parameter, i.e. 
```
docker run -it --rm -v $(pwd):/app:ro -v ~/.backport:/root/.backport --platform linux/arm64/v8 sqren/backport "$@" 
```
I still get the last error: 
```
standard_init_linux.go:219: exec user process caused: exec format error
```
I'm on Linux (Ubuntu 20.04.2 LTS)

**Comment by sqren** [comment]
Thanks for all the feedback. 
I finally bit the bullet and added [automation](https://github.com/sqren/backport/blob/main/.github/workflows/docker-build-and-push.yml#L28) for publishing docker images. This also takes care of multiple platforms (linux/amd64,linux/arm64). 

From what I can tell it should work but I'd be very happy if you can try it out

<img src="https://user-images.githubusercontent.com/209966/162050103-2f33c203-cf90-4a0e-ab36-b74dcfe59ac9.png" width="400">

**Comment by xgidiussenjensent-els** [comment]
It works now 🙂 
Thanks for the update
